using UnityEngine;
using Photon.Pun;
public class PlayerController : MonoBehaviour
{
    PhotonView pv;
    [SerializeField] GameObject bulletPrefab;
    public GameObject bullet;   
    private void Start()
    {
        pv = GetComponent<PhotonView>();
        rb = GetComponent<Rigidbody>(); // Rigidbody ê°€ì ¸ì˜¤ê¸°
    }


    public float speed = 5f;

    private void Update()
    {
        if (pv.IsMine) 
        {
            // ìºë¦­í„° ì´ë™ 
            float h = Input.GetAxis("Horizontal");
            float v = Input.GetAxis("Vertical");

            Vector3 move = new Vector3(h, 0, v) * speed * Time.deltaTime;
            transform.position += move;

            //ì´ì•Œ ë°œì‚¬ 
            if (Input.GetKeyDown(KeyCode.F)) 
            {
                Fire();
            }

            if (Input.GetKeyDown(KeyCode.G))
            {
                ApplyUpwardForce();
            }
        }
    }

    void Fire()
    {
        PhotonNetwork.Instantiate("Bullet", transform.position + new Vector3(0,2,0), transform.rotation);
        Debug.Log(" ì´ì•Œ ë°œì‚¬!!!");
    }

    [PunRPC]
    void ApplyUpwardForce_RPC()
    {
        rb.AddForce(Vector3.up * jumpForce, ForceMode.Impulse);
        Debug.Log("ğŸ”¥ ìœ„ìª½ìœ¼ë¡œ í˜ì„ ê°€í–ˆë‹¤!!!");
    }

    void ApplyUpwardForce()
    {
        pv.RPC("ApplyUpwardForce_RPC", RpcTarget.All);
    }

    public float jumpForce = 5f; // ìœ„ë¡œ ê°€í•´ì§€ëŠ” í˜
    private Rigidbody rb;
}
